

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LayoutContainer from "@/lib/LayoutContainer";
import { cn } from "@/lib/utils";
import Providers from "@/lib/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <head /> */}
      <body
        className={cn("min-h-screen w-full bg-white dark:bg-slate-900 text-slate-900 dark:text-white opacity-90", geistSans.variable, geistMono.variable, "antialiased")}
      >
        <Providers>
          <LayoutContainer>
            <Navbar />
            <div className="max-w-screen-2xl mx-auto p-4 md:px-12">
              {children}
            </div>
          </LayoutContainer>
        </Providers>
      </body>
    </html>
  );
}
